spring:
  r2dbc:
    username: server
    password:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid, profile, email, offline_access # last one for refresh tokens

application:
  security:
    keycloak:
      realm: jhipster
      admin-client-id: web_app
      admin-client-secret: web_app

jhipster:
